# Main colors
background            #fcf8ff
foreground            #1b1b21
cursor                #1b1b21
cursor_text_color     #fcf8ff
selection_background  #e2e0f9
selection_foreground  #1a1a2c
url_color             #795369

# ANSI colors
color0                #fcf8ff
color1                #ba1a1a
color2                #795369
color3                #5d5c72
color4                #585992
color5                #e9b9d3
color6                #c6c4dd
color7                #1b1b21
color8                #e4e1ec
color9                #ffdad6
color10               #ffd8ec
color11               #e2e0f9
color12               #e1dfff
color13               #454559
color14               #5f3c51
color15               #47464f

# Starship prompt bubbles
color255              #e1dfff
color254              #585992
color253              #e2e0f9
color252              #5d5c72
color251              #ffd8ec
color250              #795369
color249              #ffdad6
color248              #ba1a1a
color232              #14134a
color233              #ffffff
color234              #1a1a2c
color235              #ffffff
color236              #2f1124
color237              #ffffff
color238              #410002
color239              #ffffff
color240              #14134a
color243              #585992
color244              #ba1a1a
color245              #c8c5d0

# UI elements
active_tab_foreground   #ffffff
active_tab_background   #585992
inactive_tab_foreground #14134a
inactive_tab_background #e1dfff
active_border_color     #585992
inactive_border_color   #777680

# Marks
mark1_foreground        #14134a
mark1_background        #e1dfff
mark2_foreground        #1a1a2c
mark2_background        #e2e0f9
mark3_foreground        #2f1124
mark3_background        #ffd8ec
